cr5_group:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  #kinematics_solver: bio_ik/BioIKKinematicsPlugin

  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.01

  # --- DODANO ZA IK ---
  solve_type: Speed                # najbolj stabilna izbira za CR5
  use_consistency_limits: false    # ne omejuje IK pretirano
  collision_aware_ik: true         # OMOGOČI COLLISION CHECKING

  # (opcijsko — izboljša stabilnost)
  kinematics_solver_attempts: 5
